//
//  UserSearchResultViewController.swift
//  BrainstormTask
//
//  Created Sargis Khachatryan on 10.03.21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class UserSearchResultTableViewController: UITableViewController, UserSearchResultViewProtocol {

	var presenter: UserSearchResultPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
