//
//  UserSearchResultRouter.swift
//  BrainstormTask
//
//  Created Sargis Khachatryan on 10.03.21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class UserSearchResultRouter: UserSearchResultWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = Utility.instantiate(fromStoryboard: UserSearchResultTableViewController.self)
        let interactor = UserSearchResultInteractor()
        let router = UserSearchResultRouter()
        let presenter = UserSearchResultPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
