//
//  UserSearchResultProtocols.swift
//  BrainstormTask
//
//  Created Sargis Khachatryan on 10.03.21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol UserSearchResultWireframeProtocol: class {

}
//MARK: Presenter -
protocol UserSearchResultPresenterProtocol: class {

}

//MARK: Interactor -
protocol UserSearchResultInteractorProtocol: class {

  var presenter: UserSearchResultPresenterProtocol?  { get set }
}

//MARK: View -
protocol UserSearchResultViewProtocol: class {

  var presenter: UserSearchResultPresenterProtocol?  { get set }
}
