//
//  UserSearchResultInteractor.swift
//  BrainstormTask
//
//  Created Sargis Khachatryan on 10.03.21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class UserSearchResultInteractor: UserSearchResultInteractorProtocol {

    weak var presenter: UserSearchResultPresenterProtocol?
}
