//
//  UserSearchResultPresenter.swift
//  BrainstormTask
//
//  Created Sargis Khachatryan on 10.03.21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class UserSearchResultPresenter: UserSearchResultPresenterProtocol {

    weak private var view: UserSearchResultViewProtocol?
    var interactor: UserSearchResultInteractorProtocol?
    private let router: UserSearchResultWireframeProtocol

    init(interface: UserSearchResultViewProtocol, interactor: UserSearchResultInteractorProtocol?, router: UserSearchResultWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
