//
//  UserDetailProtocols.swift
//  BrainstormTask
//
//  Created Sargis Khachatryan on 11.03.21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol UserDetailWireframeProtocol: class {

}
//MARK: Presenter -
protocol UserDetailPresenterProtocol: class {

    var user: User { set get }
}

//MARK: Interactor -
protocol UserDetailInteractorProtocol: class {

  var presenter: UserDetailPresenterProtocol?  { get set }
}

//MARK: View -
protocol UserDetailViewProtocol: class {

  var presenter: UserDetailPresenterProtocol?  { get set }
}
