//
//  UserDetailPresenter.swift
//  BrainstormTask
//
//  Created Sargis Khachatryan on 11.03.21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class UserDetailPresenter: UserDetailPresenterProtocol {

    weak private var view: UserDetailViewProtocol?
    var interactor: UserDetailInteractorProtocol?
    private let router: UserDetailWireframeProtocol

    var user: User
    
    init(interface: UserDetailViewProtocol, interactor: UserDetailInteractorProtocol?, router: UserDetailWireframeProtocol, user: User) {
        self.view = interface
        self.interactor = interactor
        self.router = router
        self.user = user
    }

}
