//
//  UserDetailInteractor.swift
//  BrainstormTask
//
//  Created Sargis Khachatryan on 11.03.21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class UserDetailInteractor: UserDetailInteractorProtocol {

    weak var presenter: UserDetailPresenterProtocol?
}
