//
//  UserDetailViewController.swift
//  BrainstormTask
//
//  Created Sargis Khachatryan on 11.03.21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import MapKit

class UserDetailViewController: UIViewController, UserDetailViewProtocol {

    @IBOutlet fileprivate weak var mapView: MKMapView!
    @IBOutlet fileprivate weak var userImageView: UIImageView!
    @IBOutlet fileprivate weak var userNameLabel: UILabel!
    @IBOutlet fileprivate weak var userAdditionalLabel: UILabel!
    
    @IBOutlet fileprivate weak var saveUserButton: UIButton!
    @IBOutlet fileprivate weak var savdUserLabel: UILabel!
    @IBOutlet fileprivate weak var removeUserButton: UIButton!
    
    private var saveUserButtonGradient: CAGradientLayer!
    var presenter: UserDetailPresenterProtocol?
    
	override func viewDidLoad() {
        super.viewDidLoad()
        self.updateUI()
        self.updateButtons()
        self.updateUserInfo()
        self.navigationItem.title = "\(self.presenter!.user.firstName) \(self.presenter!.user.lastName)"
    }
    
    override func viewWillLayoutSubviews() {
        super.viewWillLayoutSubviews()
        self.saveUserButtonGradient.frame = self.saveUserButton.bounds
    }
    
    fileprivate func updateUI() {
        self.saveUserButtonGradient = self.saveUserButton.setGradient(colors: [#colorLiteral(red: 0.07058823529, green: 0.8941176471, blue: 0.4862745098, alpha: 1),#colorLiteral(red: 0.07058823529, green: 0.7882352941, blue: 0.431372549, alpha: 1)], angle: 90, cornerRadius: 24)
        self.saveUserButton.layer.cornerRadius = 24
        
        self.userImageView.roundedImage();
        
        self.savdUserLabel.layer.masksToBounds = true
        self.savdUserLabel.layer.cornerRadius = 24
    }
    
    fileprivate func updateButtons() {
        let isSavedUser = self.presenter!.user.isSaved
        self.saveUserButton.isHidden = isSavedUser
        self.savdUserLabel.isHidden =  !isSavedUser
        self.removeUserButton.isHidden =  !isSavedUser
    }
    
    fileprivate func updateUserInfo() {
        let user = self.presenter!.user
        
        if let url = user.pictureUrlString.url {
            self.userImageView.af.setImage(withURL: url)
        }
        
        if let url = user.pictureUrlString.url {
            self.userImageView.af.setImage(withURL: url)
        }
        self.userNameLabel.text = "\(user.firstName) \(user.lastName)"
        self.userAdditionalLabel.text = "\(user.gender), \(user.phoneNumber)\n\(user.address)"
    }

    //MARK:- Action
    @IBAction private func saveUserButtonTapped(_ sender: Any) {
        self.presenter!.user.setSavedUser()
        self.updateButtons()
    }
    
    @IBAction private func removeUserButtonTapped(_ sender: Any) {
        self.presenter!.user.removFromSavedUser()
        self.updateButtons()
    }
}
