//
//  UsersProtocols.swift
//  BrainstormTask
//
//  Created Sargis Khachatryan on 10.03.21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol UsersWireframeProtocol: class {

}
//MARK: Presenter -
protocol UsersPresenterProtocol: class {

    var interactor: UsersInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol UsersInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol UsersInteractorInputProtocol: class {

    var presenter: UsersInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol UsersViewProtocol: class {

    var presenter: UsersPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
