//
//  UsersViewController.swift
//  BrainstormTask
//
//  Created Sargis Khachatryan on 10.03.21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class UsersViewController: UIViewController, UsersViewProtocol {

	var presenter: UsersPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}

//MARK:- UITableViewDelegate, UITableViewDataSource
extension UsersViewController: UITableViewDelegate, UITableViewDataSource {
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 0
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.cell(cell: UserTableViewCell.self, for: indexPath)
        return cell
    }
}
