//
//  UsersViewController.swift
//  BrainstormTask
//
//  Created Sargis Khachatryan on 10.03.21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class UsersViewController: UIViewController, UsersViewProtocol {

	var presenter: UsersPresenterProtocol?

    fileprivate var searchController: UISearchController!
    fileprivate(set) var resultsTableController: UserSearchResultTableViewController!
    
	override func viewDidLoad() {
        super.viewDidLoad()
        self.setup()
    }

    fileprivate func setup() {
        self.resultsTableController = Utility.instantiate(fromStoryboard: UserSearchResultTableViewController.self)
        self.searchController = UISearchController(searchResultsController: resultsTableController)
        self.searchController.searchResultsUpdater = self
        self.searchController.searchBar.autocapitalizationType = .none
        self.searchController.searchResultsUpdater = self
        self.searchController.searchBar.autocapitalizationType = .none
        self.searchController.searchBar.delegate = self
        self.navigationItem.searchController = self.searchController
        self.navigationItem.hidesSearchBarWhenScrolling = false
        self.definesPresentationContext = true
        self.extendedLayoutIncludesOpaqueBars = true
    }
}

//MARK:- UITableViewDelegate, UITableViewDataSource
extension UsersViewController: UITableViewDelegate, UITableViewDataSource {
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 0
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.cell(cell: UserTableViewCell.self, for: indexPath)
        return cell
    }
}
