//
//  UsersInteractor.swift
//  BrainstormTask
//
//  Created Sargis Khachatryan on 10.03.21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class UsersInteractor: UsersInteractorInputProtocol {

    weak var presenter: UsersInteractorOutputProtocol?
    
    func getUserData(_ pageNumber: Int) {
        
        let parameters = [
            "seed" : "brainstorm",
            "results" : 20,
            "page" : pageNumber
        ] as [String : Any]
        
        BaseDataManager.shared.request(url: Endpoints.Get.user.url, parameters: parameters) { (json, error) in
            self.presenter?.rceivedUserData(json, error: error)
        }
    }
}
