//
//  UsersRouter.swift
//  BrainstormTask
//
//  Created Sargis Khachatryan on 10.03.21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class UsersRouter: UsersWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let storyBoard = UIStoryboard.init(name: "Main", bundle: nil)
        let view = storyBoard.instantiateViewController(identifier: "UsersViewController") as! UsersViewController
        let interactor = UsersInteractor()
        let router = UsersRouter()
        let presenter = UsersPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
    
    func pushToUserDtail(_ user: User) {
        let userDetailRouter = UserDetailRouter.createModule(user)
        self.viewController?.navigationController?.pushViewController(userDetailRouter, animated: true)
    }
}
